### PR TITLE
Create cleaner script for Postgres ingestion 

### PR DESCRIPTION
**Pull request by AgatheZ**
## Description

This PR aims to resolve the issue we were facing with the ingestion of CSV files into the Postgres database. The root cause was identified as the encoding of the csv files/the presence of non ASCII characters.

## Changes Made

Added a Python script that performs a UTF-8 compatibility check on each of all CSV files in the data folder.
The script copies all rows to a new CSV file, appending _preprocessed to the original filename.

## Local ingestion results 

After implementing these changes, I was able to successfully ingest all of the preprocessed CSV files locally using PgAdmin. I used the following parameters during the ingestion process:

Header: Present
Separation: Tab
Encoding: UTF-8
Quote Character: "

@heyhaleema I am happy to add extra preprocessing steps/sanity checks if you think it is necessary. I have however been able to ingest the sample vocabulary csvs from Athena with the current script.

### CODE REVIEW

**Comment by heyhaleema** [comment]
@AgatheZ Thanks, this looks great! Are you able to ingest the sample vocabulary scripts if the constraints and indices SQL scripts are run e.g., move `05_create_constraints.sql` and `06_create_indices.sql` into the `init-scripts/`, run `docker compose --env-file ./config/dev/development.env down`, delete `omop-dev-data`, and then run `docker compose --env-file ./config/dev/development.env up -d`?

**Comment by AgatheZ** [comment]
@heyhaleema 

## Ingestion of the subset vocabulary files specified in #1 
### Encountered problems 

1. **Circular dependency between `domain` and `concept` tables**: 
    - Solved by temporarily disabling and then re-enabling the foreign key constraints while ingesting these two tables. The data is validated against the constraints once they are re-enabled.

2. **Missing Data in the `concept` Table**: 
    - Encountered missing data that violates the foreign key constraints.
    Screenshot 2023-10-17 at 20 36 15

    - Suspect this is due to using a small vocabulary subset.

## Ingestion of bigger vocabulary files (SNOMED vocabulary)

- I've successfully ingested the SNOMED vocabulary that I downloaded from Athena,  **with all the constraints and indices**. It's worth noting that the SNOMED vocabulary is large in size (around 1.5 GB), so our ability to ingest it may depend on our available storage and processing capacity.

- Encountered the same circular dependency problem, that I solved using `ALTER TABLE ... DIS/EN ABLE TRIGGER ALL` before and after ingestion of the concept and domain tables. 


Screenshot 2023-10-17 at 21 12 15

###  Other updates

- I've updated the preprocessing script to avoid preprocessing files that have already been preprocessed.

**Review by heyhaleema — CHANGES_REQUESTED** [review]
Looks great, @AgatheZ 👍 Before I approve/merge, can you please move the `data_preprocessing.py` to `src/`? I think it'd be good to keep the db setup scripts separate from any data preprocessing & processing scripts (or at least for now).

Also, can you please raise an issue regarding the circular dependency?

**Comment by AgatheZ** [comment]
@heyhaleema Done!

**Review by heyhaleema — APPROVED** [review]

**Pull request merged**
